using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyTouchingDirections : MonoBehaviour
{
    public ContactFilter2D castFilter;
    public float groundDistance = 0.05f;

    CapsuleCollider2D touchingCol;

    RaycastHit2D[] groundHits = new RaycastHit2D[5]; 
    [SerializeField]
    private bool _isGrounded;

    public bool IsGrounded{get{
        return _isGrounded;
    } private set{
        _isGrounded = value;
    } }

    private void Awake()
    {
        touchingCol = GetComponent<CapsuleCollider2D>();
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        IsGrounded = touchingCol.Cast(Vector2.down, castFilter, groundHits, groundDistance) > 0;
    }

    
}
